drop table certifikat;
drop table kurz;
drop table lekce;
drop table sal;
drop table osoba;

create table certifikat(
    ID_certifikatu number generated by default as identity primary key,
    nazev varchar(50) not NULL,
    uroven varchar(20) not NULL
);

create table kurz(
    ID_kurzu number generated by default as identity primary key,
    typ varchar(20) not NULL,
    cena number default 0,
    datum_zacatku date not NULL,
    datum_konce date not NULL,
    obtiznost varchar(20) not NULL,
    popis varchar(100),
    kapacita number not NULL
);

create table lekce(
    ID_lekce number generated by default as identity primary key,
    typ varchar(20) not NULL,
    kapacita number NOT NULL,
    cena number default 0,
    obtiznost varchar(20) not NULL,
    delka_lekce number not NULL,
    popis varchar(100)
);

create table sal(
    cislo_salu number not NULL primary key,
    kapacita number not NULL,
    vybaveni varchar(200)
);

create table osoba(
    rodne_cislo char(11) not NULL primary key, /* pocita se i lomitko*/
    jmeno varchar(30) not NULL,
    prijmeni varchar(30) not NULL,
    tel_cislo number(9) not NULL,
    email varchar(30),
    psc number(5) not NULL,
    ulice varchar(30) not NULL,
    cislo_domu number not NULL,
    typ number not NULL, /*typ jestli je to klient, nstruktor, nebo oboji*/
    body number default 0,
    sleva number default 0
);